(()=>{'use strict';
const $=id=>document.getElementById(id);let pendingImages=[],bypass=false;
const css=`.evidence-box{margin-top:22px;padding-top:22px;border-top:1px solid var(--line)}.evidence-drop{border:2px dashed #b9cfe3;background:#f7fbff;border-radius:16px;padding:18px;text-align:center}.evidence-drop input{display:none}.evidence-pick{display:inline-flex;min-height:48px;align-items:center;justify-content:center;gap:8px;padding:11px 17px;border:0;border-radius:12px;background:#2568a9;color:#fff;font-weight:700;cursor:pointer}.evidence-help{margin-top:9px;font-size:12px;color:var(--muted);line-height:1.55}.evidence-preview{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin-top:12px}.evidence-thumb{position:relative;aspect-ratio:1;border-radius:12px;overflow:hidden;background:#eaf2f8;border:1px solid var(--line)}.evidence-thumb img{width:100%;height:100%;object-fit:cover}.evidence-thumb span{position:absolute;left:4px;right:4px;bottom:4px;background:rgba(0,0,0,.62);color:#fff;border-radius:7px;padding:3px 5px;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}@media(max-width:600px){.evidence-preview{grid-template-columns:repeat(2,minmax(0,1fr))}.evidence-drop{padding:15px 12px}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function mount(){const host=$('dynamicFields');if(!host||$('evidenceInput'))return;const box=document.createElement('div');box.className='evidence-box';box.innerHTML=`<h3>📷 ภาพหลักฐาน / ภาพผลงาน</h3><div class="evidence-drop"><label class="evidence-pick" for="evidenceInput">📷 เลือกภาพหรือถ่ายรูป</label><input id="evidenceInput" type="file" accept="image/*" multiple><div class="evidence-help">แนบได้สูงสุด 4 ภาพต่อรายการ ระบบจะย่อภาพอัตโนมัติเพื่อให้ส่งจากโทรศัพท์ได้เร็วขึ้น<br>ภาพจะถูกเก็บใน Google Drive ของโรงเรียน และไม่เพิ่มคอลัมน์ในไฟล์ TCAS ทั้ง 4 ประเภท</div><div id="evidencePreview" class="evidence-preview"></div></div>`;host.appendChild(box);$('evidenceInput').addEventListener('change',preview)}
function preview(e){let files=[...e.target.files];if(files.length>4){alert('แนบภาพได้ไม่เกิน 4 ภาพต่อรายการ');e.target.value='';files=[]}const w=$('evidencePreview');w.innerHTML='';files.forEach(f=>{const d=document.createElement('div');d.className='evidence-thumb';const img=document.createElement('img');img.src=URL.createObjectURL(f);img.onload=()=>URL.revokeObjectURL(img.src);const s=document.createElement('span');s.textContent=f.name;d.append(img,s);w.appendChild(d)})}
function fileToImage(file){return new Promise((res,rej)=>{const u=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(u);res(img)};img.onerror=()=>{URL.revokeObjectURL(u);rej(new Error('ไม่สามารถอ่านภาพ '+file.name+' ได้ กรุณาใช้ไฟล์ JPG/PNG หรือถ่ายภาพใหม่'))};img.src=u})}
async function compress(file){if(!file.type.startsWith('image/'))throw new Error('กรุณาเลือกเฉพาะไฟล์ภาพ');const img=await fileToImage(file),max=1600,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);let q=.82,data=c.toDataURL('image/jpeg',q);while(data.length>2800000&&q>.48){q-=.08;data=c.toDataURL('image/jpeg',q)}if(data.length>3500000)throw new Error('ภาพ '+file.name+' มีขนาดใหญ่เกินไป กรุณาใช้ภาพขนาดเล็กลง');return{name:file.name,data:data}}
const obs=new MutationObserver(mount);const host=$('dynamicFields');if(host)obs.observe(host,{childList:true,subtree:false});mount();
const entry=$('entryForm');if(entry)entry.addEventListener('submit',async e=>{if(bypass){bypass=false;return}const input=$('evidenceInput'),files=input?[...input.files]:[];if(!files.length){pendingImages=[];return}e.preventDefault();e.stopImmediatePropagation();$('loader')?.classList.add('show');try{pendingImages=[];for(const f of files)pendingImages.push(await compress(f));bypass=true;entry.requestSubmit()}catch(err){alert(err.message);pendingImages=[]}finally{$('loader')?.classList.remove('show')}},true);
const pf=$('postForm');if(pf){const native=HTMLFormElement.prototype.submit;pf.submit=function(){try{const action=this.elements.action.value;if((action==='save'||action==='update')&&pendingImages.length){const p=JSON.parse(this.elements.payload.value||'{}');p.images=pendingImages;this.elements.payload.value=JSON.stringify(p);pendingImages=[]}}catch(_){pendingImages=[]}return native.call(this)}}
})();